# Copyright 2024 Heiko Schlittermann <hs@schlittermann.de>
# SPDX-License-Identifier: Apache-2.0

# Example config for gogogo
#
# Defaults are shown as #key: value, examples are prefixed as such.
#

# The Module name of the commands that should be released. If empty, it
# is taken from the file referenced by `go env GOMOD`
# e.g. module: go.schlittermann.de module: 
#
#module:

# What do we build actually?
build:

  # The commands to be built. If unset or empty, the command is assumed to be in
  # the module's top level directory.
  # e.g. - cmd/foo
  #commands: []
  commands:
    - cmd/cert-proxy-client
    - cmd/cert-proxy-server

  # The targets (pairs of <os>/<arch> to be built.  See `go tool dist
  # list` for a complete list.  If unset or empty, the values of
  # `go env GOOS` and `go env GOARCH` are used.
  # e.g. - windows/arm
  #targets: []
  targets:
    - linux/amd64
    - linux/arm64
    - windows/amd64

  # The tests to be run.
  #test:
  #  skip: false
  #  run: ""
  #  flags: []
  #  args: []

# How to access the repo
repo:

  # The API URL of the repo.
  # e.g. apiurl: https://git.schlittermann.de/api/v1
  #apiurl: 
  apiurl: https://git.schlittermann.de/api/v1

  # The API might respond with a redirect. This option allows to
  # restrict the redirect targets (defaults blindly follow any redirect).
  # The restriction is a list of permitted redirect target prefixes (schema://host/path).
  # e.g. - https://forgejo.schlittermann.de/
  #restrict30x:

  # The owner (organization) of the repo.
  # e.g. owner: heiko
  owner: heiko

  # The name of the repo.
  # e.g. name: gogogo
  name: cert-proxy

  # the API token (PAT) to access the repo (write access is required)
  # For syntax, please refer to https://go.schlittermann.de/heiko/secret
  # e.g. token: plain:71557d54792f…ab1c2ca20e37c
  token: file:$HOME/.tokens/git.schlittermann.de

# Additional environment variables
env:
  CGO_ENABLED: 0
  # e.g GOPRIVATE: "*.schlittermann.de"

# vim:set ft=yaml:
