name: mod-nag (Scheduled)

on:
  schedule:
    - cron: '25 4 * * *'
  workflow_dispatch:

jobs:
  mod-nag:
    uses: ius/workflows/.forgejo/workflows/mod-nag.yaml@master
    with:
      scan_branches: '["master"]'
