#!/bin/bash

set -e
export LC_ALL=C

source vars
install -d ca ca/newcerts
install -d -m 700 ca/private
touch ca/index.txt

test -f ca/private/cakey.pem \
|| openssl genrsa -des3 -out ca/private/cakey.pem 4096

test -f ca/cacsr.pem \
|| openssl req -new -out ca/cacsr.pem \
    -days 3650 \
    -key ca/private/cakey.pem \
    -subj "/C=$CA_DEFAULT_C/ST=$CA_DEFAULT_ST/L=$CA_DEFAULT_L/O=$CA_DEFAULT_O/OU=$CA_DEFAULT_OU/CN=CA"

test -f ca/cacrt.pem \
|| openssl ca -selfsign -days 3650 -keyfile ca/private/cakey.pem \
   -out ca/cacert.pem \
   -create_serial \
   -infiles ca/cacsr.pem
