Document: cert-proxy
Title: Debian cert-proxy Manual
Author: <insert document author here>
Abstract: This manual describes what cert-proxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cert-proxy/cert-proxy.sgml.gz

Format: postscript
Files: /usr/share/doc/cert-proxy/cert-proxy.ps.gz

Format: text
Files: /usr/share/doc/cert-proxy/cert-proxy.text.gz

Format: HTML
Index: /usr/share/doc/cert-proxy/html/index.html
Files: /usr/share/doc/cert-proxy/html/*.html
